# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49c0cfed369a8705fbd2842f18acf1ee263954ba0600f8b0e7a1caea5bd1354cb989cf840ece2106690162db60ca64c17146b3fadc5f7e952aa50dda9e49d8ca

test:
  secret_key_base: 9f23acb7b204421eb7caf7eb7d5909dd54a0c84f50000f46d60da64af55750f315a9aac0269013b7902230502633420b6bb33da15285d7a5053780040cfadc05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
